public class Q3
{

	public static void main(String []args){
		System.out.println("\nCourse\t\t\t\tCredit Hours\t\tGrade");
		System.out.println("Introduction To Computing\t\t3\t\tF");
		System.out.println("COMPUTER PROGRAMMING\t\t\t3\t\tC");
		System.out.println("COMPUTER PROGRAMMING LAB\t\t1\t\tA");
		System.out.println("CALCULUS-I\t\t\t\t3\t\tC+");
		System.out.println("FRESHMAN ENGLISH\t\t\t3\t\tB");
		System.out.println("ISLAMIC STUDIES\t\t\t\t2\t\tB");
		System.out.println("\nGPA : 2.21\n\n\n");
		System.out.println("Summary");
		System.out.println("Credit Earned	13");
		System.out.println("CGPA	2.21");
	}


}