public class Q4
{

	public static void main(String []args){
		System.out.println("\nFrom matric to Now I have done much Learning,");
		System.out.println("I was from start intrust in Sports ,as well as");
		System.out.println("Electronic Components which was a craze towa-");
		System.out.println("rds me but now I am doing BSCS from Maju Uni-");
		System.out.println("versity but now I am studing in Computer Scien-");
		System.out.println("ce Progam things here are they have are very"); 
		System.out.println("contrasted feilds and give Opertunity of Bringing");
		System.out.println("up myselfs\nThanks\n" 
						+ "\nYour Sincrly \nMuhammad Moiz");

/*Write a program that displays your educational background starting from
matriculation. The information should also include the name of your institute and
grade.
*/

	}


}